version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "730335578330"
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPOSITORY_NAME: "crypto-app"
    ECS_CONTAINER_NAME: "crypto-app"
    ECS_CLUSTER: "your-ecs-cluster-name"
    SERVICE_NAME: "your-service-name"
    TASK_DEFINITION_FAMILY: "your-task-definition-family"

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - REPOSITORY_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Using image tag: $IMAGE_TAG

  build:
    commands:
      - echo Changing to project directory...
      - cd monolith-aws-microservice-project

      - echo Building the Docker image from subfolder...
      - docker build -t "$REPOSITORY_URI:$IMAGE_TAG" .
      - docker tag "$REPOSITORY_URI:$IMAGE_TAG" "$REPOSITORY_URI:latest"

  post_build:
    commands:
      - echo Pushing Docker images...
      - docker push "$REPOSITORY_URI:$IMAGE_TAG"
      - docker push "$REPOSITORY_URI:latest"

      - echo Creating imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$ECS_CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

      - echo Updating task-definition.json template in subfolder...
      - sed -i "s|REPOSITORY_URI_PLACEHOLDER|${REPOSITORY_URI}:${IMAGE_TAG}|g" task-definition.json

      - echo Registering new ECS task definition...
      - REGISTER_OUTPUT=$(aws ecs register-task-definition --region "$AWS_DEFAULT_REGION" --cli-input-json file://task-definition.json)

      - echo Extracting new task definition revision...
      - NEW_REV=$(echo $REGISTER_OUTPUT | jq '.taskDefinition.revision')

      - echo Deploying new revision $NEW_REV to ECS service...
      - aws ecs update-service \
          --cluster "$ECS_CLUSTER" \
          --service "$SERVICE_NAME" \
          --task-definition "${TASK_DEFINITION_FAMILY}:${NEW_REV}" \
          --force-new-deployment \
          --region "$AWS_DEFAULT_REGION"

artifacts:
  files:
    - monolith-aws-microservice-project/imagedefinitions.json
